version: "3"

services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        ports:
            - "15672:15672"
            - "5672:5672"
    web:
        hostname: 'crawler'
        build: 
            context: server
    worker:
        build: 
            context: worker

    client:
        build:
            context: .
            dockerfile: ./client/Dockerfile
