# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messages_pb2 as messages__pb2


class WikiCrawlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Crawl = channel.unary_stream(
                '/WikiCrawler/Crawl',
                request_serializer=messages__pb2.Task.SerializeToString,
                response_deserializer=messages__pb2.Result.FromString,
                )


class WikiCrawlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Crawl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WikiCrawlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Crawl': grpc.unary_stream_rpc_method_handler(
                    servicer.Crawl,
                    request_deserializer=messages__pb2.Task.FromString,
                    response_serializer=messages__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WikiCrawler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WikiCrawler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Crawl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/WikiCrawler/Crawl',
            messages__pb2.Task.SerializeToString,
            messages__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
